version: '3.3'

services:
  app:
    image: go-app
    container_name: go-app
    restart: always
    ports:
      - '6422:8080'
    environment:
      RUN_MODE: debug

networks:
  default:
    external:
      name: tmp
